enum ETxType {
  UNLOCK_FUNDS = "UNLOCK_FUNDS",
  TRANSFER_TOKENS = "TRANSFER_TOKENS",
  WITHDRAW = "WITHDRAW",
  INVEST = "INVEST",
  UPGRADE = "UPGRADE",
  ETO_SET_DATE = "ETO_SET_DATE",
  SIGN_INVESTMENT_AGREEMENT = "SIGN_INVESTMENT_AGREEMENT",
  USER_CLAIM = "USER_CLAIM",
  INVESTOR_ACCEPT_PAYOUT = "INVESTOR_ACCEPT_PAYOUT",
  INVESTOR_REDISTRIBUTE_PAYOUT = "INVESTOR_REDISTRIBUTE_PAYOUT",
  NEUR_REDEEM = "NEUR_REDEEM",
  INVESTOR_REFUND = "INVESTOR_REFUND",
  NOMINEE_THA_SIGN = "NOMINEE_THA_SIGN",
  NOMINEE_RAAA_SIGN = "NOMINEE_RAAA_SIGN",
  NOMINEE_ISHA_SIGN = "NOMINEE_ISHA_SIGN",
  SHAREHOLDER_RESOLUTIONS_VOTE = "SHAREHOLDER_RESOLUTIONS_VOTE",
  EXECUTE_RESOLUTION = "EXECUTE_RESOLUTION",
}

export { ETxType };
