export enum ECountries {
  AFGHANISTAN = "AF",
  ALAND_ISLANDS = "AX",
  ALBANIA = "AL",
  ALGERIA = "DZ",
  AMERICAN_SAMOA = "AS",
  ANDORRA = "AD",
  ANGOLA = "AO",
  ANGUILLA = "AI",
  ANTARCTICA = "AQ",
  ANTIGUA_AND_BARBUDA = "AG",
  ARGENTINA = "AR",
  ARMENIA = "AM",
  ARUBA = "AW",
  AUSTRALIA = "AU",
  AUSTRIA = "AT",
  AZERBAIJAN = "AZ",
  BAHAMAS = "BS",
  BAHRAIN = "BH",
  BANGLADESH = "BD",
  BARBADOS = "BB",
  BELARUS = "BY",
  BELGIUM = "BE",
  BELIZE = "BZ",
  BENIN = "BJ",
  BERMUDA = "BM",
  BHUTAN = "BT",
  BOLIVIA = "BO",
  BOSNIA_AND_HERZEGOVINA = "BA",
  BOTSWANA = "BW",
  BOUVET_ISLAND = "BV",
  BRAZIL = "BR",
  BRITISH_INDIAN_OCEAN_TERRITORY = "IO",
  BRUNEI_DARUSSALAM = "BN",
  BULGARIA = "BG",
  BURKINA_FASO = "BF",
  BURUNDI = "BI",
  CAMBODIA = "KH",
  CAMEROON = "CM",
  CANADA = "CA",
  CAPE_VERDE = "CV",
  CAYMAN_ISLANDS = "KY",
  CENTRAL_AFRICAN_REPUBLIC = "CF",
  CHAD = "TD",
  CHILE = "CL",
  CHINA = "CN",
  CHRISTMAS_ISLAND = "CX",
  COCOS_KEELING_ISLANDS = "CC",
  COLOMBIA = "CO",
  COMOROS = "KM",
  CONGO = "CG",
  CONGO_DEMOCRATIC_REPUBLIC = "CD",
  COOK_ISLANDS = "CK",
  COSTA_RICA = "CR",
  COTE_DIVOIRE = "CI",
  CROATIA = "HR",
  CUBA = "CU",
  CYPRUS = "CY",
  CZECH_REPUBLIC = "CZ",
  DENMARK = "DK",
  DJIBOUTI = "DJ",
  DOMINICA = "DM",
  DOMINICAN_REPUBLIC = "DO",
  ECUADOR = "EC",
  EGYPT = "EG",
  EL_SALVADOR = "SV",
  EQUATORIAL_GUINEA = "GQ",
  ERITREA = "ER",
  ESTONIA = "EE",
  ETHIOPIA = "ET",
  FALKLAND_ISLANDS = "FK",
  FAROE_ISLANDS = "FO",
  FIJI = "FJ",
  FINLAND = "FI",
  FRANCE = "FR",
  FRENCH_GUIANA = "GF",
  FRENCH_POLYNESIA = "PF",
  FRENCH_SOUTHERN_TERRITORIES = "TF",
  GABON = "GA",
  GAMBIA = "GM",
  GEORGIA = "GE",
  GERMANY = "DE",
  GHANA = "GH",
  GIBRALTAR = "GI",
  GREECE = "GR",
  GREENLAND = "GL",
  GRENADA = "GD",
  GUADELOUPE = "GP",
  GUAM = "GU",
  GUATEMALA = "GT",
  GUERNSEY = "GG",
  GUINEA = "GN",
  GUINEA_BISSAU = "GW",
  GUYANA = "GY",
  HAITI = "HT",
  HEARD_ISLAND_MCDONALD_ISLANDS = "HM",
  HOLY_SEE_VATICAN_CITY_STATE = "VA",
  HONDURAS = "HN",
  HONG_KONG = "HK",
  HUNGARY = "HU",
  ICELAND = "IS",
  INDIA = "IN",
  INDONESIA = "ID",
  IRAN = "IR",
  IRAQ = "IQ",
  IRELAND = "IE",
  ISLE_OF_MAN = "IM",
  ISRAEL = "IL",
  ITALY = "IT",
  JAMAICA = "JM",
  JAPAN = "JP",
  JERSEY = "JE",
  JORDAN = "JO",
  KAZAKHSTAN = "KZ",
  KENYA = "KE",
  KIRIBATI = "KI",
  NORTH_KOREA = "KP",
  SOUTH_KOREA = "KR",
  KUWAIT = "KW",
  KYRGYZSTAN = "KG",
  LAO_PEOPLES_DEMOCRATIC_REPUBLIC = "LA",
  LATVIA = "LV",
  LEBANON = "LB",
  LESOTHO = "LS",
  LIBERIA = "LR",
  LIBYAN_ARAB_JAMAHIRIYA = "LY",
  LIECHTENSTEIN = "LI",
  LITHUANIA = "LT",
  LUXEMBOURG = "LU",
  MACAO = "MO",
  MACEDONIA = "MK",
  MADAGASCAR = "MG",
  MALAWI = "MW",
  MALAYSIA = "MY",
  MALDIVES = "MV",
  MALI = "ML",
  MALTA = "MT",
  MARSHALL_ISLANDS = "MH",
  MARTINIQUE = "MQ",
  MAURITANIA = "MR",
  MAURITIUS = "MU",
  MAYOTTE = "YT",
  MEXICO = "MX",
  MICRONESIA = "FM",
  MOLDOVA = "MD",
  MONACO = "MC",
  MONGOLIA = "MN",
  MONTENEGRO = "ME",
  MONTSERRAT = "MS",
  MOROCCO = "MA",
  MOZAMBIQUE = "MZ",
  MYANMAR = "MM",
  NAMIBIA = "NA",
  NAURU = "NR",
  NEPAL = "NP",
  NETHERLANDS = "NL",
  NETHERLANDS_ANTILLES = "AN",
  NEW_CALEDONIA = "NC",
  NEW_ZEALAND = "NZ",
  NICARAGUA = "NI",
  NIGER = "NE",
  NIGERIA = "NG",
  NIUE = "NU",
  NORFOLK_ISLAND = "NF",
  NORTHERN_MARIANA_ISLANDS = "MP",
  NORWAY = "NO",
  OMAN = "OM",
  PAKISTAN = "PK",
  PALAU = "PW",
  PALESTINIAN_TERRITORY = "PS",
  PANAMA = "PA",
  PAPUA_NEW_GUINEA = "PG",
  PARAGUAY = "PY",
  PERU = "PE",
  PHILIPPINES = "PH",
  PITCAIRN = "PN",
  POLAND = "PL",
  PORTUGAL = "PT",
  PUERTO_RICO = "PR",
  QATAR = "QA",
  REUNION = "RE",
  ROMANIA = "RO",
  RUSSIAN_FEDERATION = "RU",
  RWANDA = "RW",
  SAINT_BARTHELEMY = "BL",
  SAINT_HELENA = "SH",
  SAINT_KITTS_AND_NEVIS = "KN",
  SAINT_LUCIA = "LC",
  SAINT_MARTIN = "MF",
  SAINT_PIERRE_AND_MIQUELON = "PM",
  SAINT_VINCENT_AND_GRENADINES = "VC",
  SAMOA = "WS",
  SAN_MARINO = "SM",
  SAO_TOME_AND_PRINCIPE = "ST",
  SAUDI_ARABIA = "SA",
  SENEGAL = "SN",
  SERBIA = "RS",
  SEYCHELLES = "SC",
  SIERRA_LEONE = "SL",
  SINGAPORE = "SG",
  SLOVAKIA = "SK",
  SLOVENIA = "SI",
  SOLOMON_ISLANDS = "SB",
  SOMALIA = "SO",
  SOUTH_AFRICA = "ZA",
  SOUTH_GEORGIA_AND_SANDWICH_ISL = "GS",
  SPAIN = "ES",
  SRI_LANKA = "LK",
  SUDAN = "SD",
  SURINAME = "SR",
  SVALBARD_AND_JAN_MAYEN = "SJ",
  SWAZILAND = "SZ",
  SWEDEN = "SE",
  SWITZERLAND = "CH",
  SYRIAN_ARAB_REPUBLIC = "SY",
  TAIWAN = "TW",
  TAJIKISTAN = "TJ",
  TANZANIA = "TZ",
  THAILAND = "TH",
  TIMOR_LESTE = "TL",
  TOGO = "TG",
  TOKELAU = "TK",
  TONGA = "TO",
  TRINIDAD_AND_TOBAGO = "TT",
  TUNISIA = "TN",
  TURKEY = "TR",
  TURKMENISTAN = "TM",
  TURKS_AND_CAICOS_ISLANDS = "TC",
  TUVALU = "TV",
  UGANDA = "UG",
  UKRAINE = "UA",
  UNITED_ARAB_EMIRATES = "AE",
  UNITED_KINGDOM = "GB",
  UNITED_STATES = "US",
  UNITED_STATES_OUTLYING_ISLANDS = "UM",
  URUGUAY = "UY",
  UZBEKISTAN = "UZ",
  VANUATU = "VU",
  VENEZUELA = "VE",
  VIET_NAM = "VN",
  VIRGIN_ISLANDS_BRITISH = "VG",
  VIRGIN_ISLANDS_US = "VI",
  WALLIS_AND_FUTUNA = "WF",
  WESTERN_SAHARA = "EH",
  YEMEN = "YE",
  ZAMBIA = "ZM",
  ZIMBABWE = "ZW",
}

export const COUNTRIES = {
  AF: "Afghanistan",
  AX: "ÅLand Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia, Plurinational State Of",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, The Democratic Republic Of The",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "CÔTe D'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island And Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle Of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KO: "Kosovo",
  KP: "Korea, Democratic People'S Republic Of",
  KR: "Korea, Republic Of",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People'S Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia, The Former Yugoslav Republic Of",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States Of",
  MD: "Moldova, Republic Of",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "RÉUnion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  BL: "Saint Barthélemy",
  SH: "Saint Helena, Ascension And Tristan Da Cunha",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre And Miquelon",
  VC: "Saint Vincent And The Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia And The South Sandwich Islands",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard And Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan, Province Of China",
  TJ: "Tajikistan",
  TZ: "Tanzania, United Republic Of",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela, Bolivarian Republic Of",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis And Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const NATIONALITIES = {
  AF: "Afghan",
  AL: "Albanian",
  DZ: "Algerian",
  US: "American",
  AS: "American Samoan",
  AD: "Andorran",
  AO: "Angolan",
  AI: "Anguillian",
  AQ: "Antarctic",
  AG: "Antiguan, Barbudan",
  AR: "Argentinean",
  AM: "Armenian",
  AW: "Aruban",
  AU: "Australian",
  AT: "Austrian",
  AZ: "Azerbaijani",
  BS: "Bahamian",
  BH: "Bahraini",
  BD: "Bangladeshi",
  BB: "Barbadian",
  BL: "Barthélemois",
  BY: "Belarusian",
  BE: "Belgian",
  BZ: "Belizean",
  BJ: "Beninese",
  BM: "Bermudian",
  BT: "Bhutanese",
  IO: "BIOT",
  BO: "Bolivian",
  BA: "Bosnian, Herzegovinian",
  BV: "Bouvet Island",
  BR: "Brazilian",
  GB: "British",
  VG: "British Virgin Island",
  BN: "Bruneian",
  BG: "Bulgarian",
  BF: "Burkinabe",
  MM: "Burmese",
  BI: "Burundian",
  KH: "Cambodian",
  CM: "Cameroonian",
  CA: "Canadian",
  CV: "Cape Verdian",
  KY: "Caymanian",
  CF: "Central African",
  TD: "Chadian",
  GG: "Channel Islander (GG)",
  JE: "Channel Islander (JE)",
  CL: "Chilean",
  CN: "Chinese",
  CX: "Christmas Island",
  CC: "Cocos Islander",
  CO: "Colombian",
  KM: "Comoran",
  CG: "Congolese (CG)",
  CD: "Congolese (CD)",
  CK: "Cook Islander",
  CR: "Costa Rican",
  HR: "Croatian",
  CU: "Cuban",
  CY: "Cypriot",
  CZ: "Czech",
  DK: "Danish",
  DJ: "Djibouti",
  DM: "Dominican (DM)",
  DO: "Dominican (DO)",
  NL: "Dutch",
  TL: "East Timorese",
  EC: "Ecuadorean",
  EG: "Egyptian",
  AE: "Emirati",
  GQ: "Equatorial Guinean",
  ER: "Eritrean",
  EE: "Estonian",
  ET: "Ethiopian",
  FK: "Falkland Islander",
  FO: "Faroese",
  FJ: "Fijian",
  PH: "Filipino",
  FI: "Finnish",
  FR: "French",
  GF: "French Guianese",
  PF: "French Polynesian",
  GA: "Gabonese",
  GM: "Gambian",
  GE: "Georgian",
  DE: "German",
  GH: "Ghanaian",
  GI: "Gibraltar",
  GR: "Greek",
  GL: "Greenlandic",
  GD: "Grenadian",
  GP: "Guadeloupian",
  GU: "Guamanian",
  GT: "Guatemalan",
  GW: "Guinea-Bissauan",
  GN: "Guinean",
  GY: "Guyanese",
  HT: "Haitian",
  HM: "Heard and McDonald Islander",
  HN: "Honduran",
  HK: "Hong Kongese",
  HU: "Hungarian",
  KI: "I-Kiribati",
  IS: "Icelander",
  IN: "Indian",
  ID: "Indonesian",
  IR: "Iranian",
  IQ: "Iraqi",
  IE: "Irish",
  IL: "Israeli",
  IT: "Italian",
  CI: "Ivorian",
  JM: "Jamaican",
  JP: "Japanese",
  JO: "Jordanian",
  KZ: "Kazakhstani",
  KE: "Kenyan",
  KG: "Kirghiz",
  KN: "Kittian and Nevisian",
  KO: "Kosovan",
  KW: "Kuwaiti",
  LA: "Laotian",
  LV: "Latvian",
  LB: "Lebanese",
  LR: "Liberian",
  LY: "Libyan",
  LI: "Liechtensteiner",
  LT: "Lithuanian",
  LU: "Luxembourger",
  MO: "Macanese",
  MK: "Macedonian",
  MG: "Malagasy",
  MW: "Malawian",
  MY: "Malaysian",
  MV: "Maldivan",
  ML: "Malian",
  MT: "Maltese",
  IM: "Manx",
  MH: "Marshallese",
  MR: "Mauritanian",
  MU: "Mauritian",
  MX: "Mexican",
  FM: "Micronesian",
  MD: "Moldovan",
  MC: "Monegasque",
  MN: "Mongolian",
  ME: "Montenegrin",
  MS: "Montserratian",
  MA: "Moroccan",
  LS: "Mosotho",
  BW: "Motswana",
  MZ: "Mozambican",
  NA: "Namibian",
  NR: "Nauruan",
  NP: "Nepalese",
  AN: "Netherlands Antilles",
  NC: "New Caledonian",
  NZ: "New Zealander",
  VU: "Ni-Vanuatu",
  NI: "Nicaraguan",
  NG: "Nigerian",
  NE: "Nigerien",
  NU: "Niuean",
  NF: "Norfolk Islander",
  KP: "North Korean",
  MP: "Northern Marianan",
  NO: "Norwegian",
  OM: "Omani",
  PK: "Pakistani",
  PW: "Palauan",
  PS: "Palestinian",
  PA: "Panamanian",
  PG: "Papua New Guinean",
  PY: "Paraguayan",
  PE: "Peruvian",
  PN: "Pitcairn Islander",
  PL: "Polish",
  PT: "Portuguese",
  PR: "Puerto Rican",
  QA: "Qatari",
  RO: "Romanian",
  RU: "Russian",
  RW: "Rwandan",
  EH: "Sahrawi",
  SH: "Saint Helenian",
  LC: "Saint Lucian",
  VC: "Saint Vincentian",
  MF: "Saint-Martinoise",
  SV: "Salvadoran",
  SM: "Sammarinese",
  WS: "Samoan",
  ST: "Sao Tomean",
  SA: "Saudi Arabian",
  SN: "Senegalese",
  RS: "Serbian",
  SC: "Seychellois",
  SL: "Sierra Leonean",
  SG: "Singaporean",
  SK: "Slovak",
  SI: "Slovene",
  SB: "Solomon Islander",
  SO: "Somali",
  ZA: "South African",
  GS: "South Georgia and the South Sandwich Islander",
  KR: "South Korean",
  ES: "Spanish",
  LK: "Sri Lankan",
  SD: "Sudanese",
  SR: "Surinamer",
  SJ: "Svalbard",
  SZ: "Swazi",
  SE: "Swedish",
  CH: "Swiss",
  SY: "Syrian",
  TJ: "Tadzhik",
  TW: "Taiwanese",
  TZ: "Tanzanian",
  TH: "Thai",
  TG: "Togolese",
  TK: "Tokelauan",
  TO: "Tongan",
  TT: "Trinidadian",
  TN: "Tunisian",
  TR: "Turkish",
  TM: "Turkmen",
  TC: "Turks and Caicos Island",
  TV: "Tuvaluan",
  VI: "U.S. Virgin Island",
  UG: "Ugandan",
  UA: "Ukrainian",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguayan",
  UZ: "Uzbekistani",
  VA: "Vatican",
  VE: "Venezuelan",
  VN: "Vietnamese",
  WF: "Wallis and Futuna Islander",
  YE: "Yemeni",
  ZM: "Zambian",
  ZW: "Zimbabwean",
  AX: "Åland Island",
};
