import { Dictionary, TTranslatedString } from "../../types";

export enum EUSState {
  ALABAMA = "AL",
  ALASKA = "AK",
  AMERICAN_SAMOA = "AS",
  ARIZONA = "AZ",
  ARKANSAS = "AR",
  CALIFORNIA = "CA",
  COLORADO = "CO",
  CONNECTICUT = "CT",
  DELAWARE = "DE",
  DISTRICT_OF_COLUMBIA = "DC",
  FEDERATED_STATES_OF_MICRONESIA = "FM",
  FLORIDA = "FL",
  GEORGIA = "GA",
  GUAM = "GU",
  HAWAII = "HI",
  IDAHO = "ID",
  ILLINOIS = "IL",
  INDIANA = "IN",
  IOWA = "IA",
  KANSAS = "KS",
  KENTUCKY = "KY",
  LOUISIANA = "LA",
  MAINE = "ME",
  MARSHALL_ISLANDS = "MH",
  MARYLAND = "MD",
  MASSACHUSETTS = "MA",
  MICHIGAN = "MI",
  MINNESOTA = "MN",
  MISSISSIPPI = "MS",
  MISSOURI = "MO",
  MONTANA = "MT",
  NEBRASKA = "NE",
  NEVADA = "NV",
  NEW_HAMPSHIRE = "NH",
  NEW_JERSEY = "NJ",
  NEW_MEXICO = "NM",
  NEW_YORK = "NY",
  NORTH_CAROLINA = "NC",
  NORTH_DAKOTA = "ND",
  NORTHERN_MARIANA_ISLANDS = "MP",
  OHIO = "OH",
  OKLAHOMA = "OK",
  OREGON = "OR",
  PALAU = "PW",
  PENNSYLVANIA = "PA",
  PUERTO_RICO = "PR",
  RHODE_ISLAND = "RI",
  SOUTH_CAROLINA = "SC",
  SOUTH_DAKOTA = "SD",
  TENNESSEE = "TN",
  TEXAS = "TX",
  UTAH = "UT",
  VERMONT = "VT",
  VIRGIN_ISLANDS = "VI",
  VIRGINIA = "VA",
  WASHINGTON = "WA",
  WEST_VIRGINIA = "WV",
  WISCONSIN = "WI",
  WYOMING = "WY",
}

export const US_STATES: Dictionary<TTranslatedString, EUSState> = {
  [EUSState.ALABAMA]: "Alabama",
  [EUSState.ALASKA]: "Alaska",
  [EUSState.AMERICAN_SAMOA]: "American Samoa",
  [EUSState.ARIZONA]: "Arizona",
  [EUSState.ARKANSAS]: "Arkansas",
  [EUSState.CALIFORNIA]: "California",
  [EUSState.COLORADO]: "Colorado",
  [EUSState.CONNECTICUT]: "Connecticut",
  [EUSState.DELAWARE]: "Delaware",
  [EUSState.DISTRICT_OF_COLUMBIA]: "District Of Columbia",
  [EUSState.FEDERATED_STATES_OF_MICRONESIA]: "Federated States Of Micronesia",
  [EUSState.FLORIDA]: "Florida",
  [EUSState.GEORGIA]: "Georgia",
  [EUSState.GUAM]: "Guam",
  [EUSState.HAWAII]: "Hawaii",
  [EUSState.IDAHO]: "Idaho",
  [EUSState.ILLINOIS]: "Illinois",
  [EUSState.INDIANA]: "Indiana",
  [EUSState.IOWA]: "Iowa",
  [EUSState.KANSAS]: "Kansas",
  [EUSState.KENTUCKY]: "Kentucky",
  [EUSState.LOUISIANA]: "Louisiana",
  [EUSState.MAINE]: "Maine",
  [EUSState.MARSHALL_ISLANDS]: "Marshall Islands",
  [EUSState.MARYLAND]: "Maryland",
  [EUSState.MASSACHUSETTS]: "Massachusetts",
  [EUSState.MICHIGAN]: "Michigan",
  [EUSState.MINNESOTA]: "Minnesota",
  [EUSState.MISSISSIPPI]: "Mississippi",
  [EUSState.MISSOURI]: "Missouri",
  [EUSState.MONTANA]: "Montana",
  [EUSState.NEBRASKA]: "Nebraska",
  [EUSState.NEVADA]: "Nevada",
  [EUSState.NEW_HAMPSHIRE]: "New Hampshire",
  [EUSState.NEW_JERSEY]: "New Jersey",
  [EUSState.NEW_MEXICO]: "New Mexico",
  [EUSState.NEW_YORK]: "New York",
  [EUSState.NORTH_CAROLINA]: "North Carolina",
  [EUSState.NORTH_DAKOTA]: "North Dakota",
  [EUSState.NORTHERN_MARIANA_ISLANDS]: "Northern Mariana Islands",
  [EUSState.OHIO]: "Ohio",
  [EUSState.OKLAHOMA]: "Oklahoma",
  [EUSState.OREGON]: "Oregon",
  [EUSState.PALAU]: "Palau",
  [EUSState.PENNSYLVANIA]: "Pennsylvania",
  [EUSState.PUERTO_RICO]: "Puerto Rico",
  [EUSState.RHODE_ISLAND]: "Rhode Island",
  [EUSState.SOUTH_CAROLINA]: "South Carolina",
  [EUSState.SOUTH_DAKOTA]: "South Dakota",
  [EUSState.TENNESSEE]: "Tennessee",
  [EUSState.TEXAS]: "Texas",
  [EUSState.UTAH]: "Utah",
  [EUSState.VERMONT]: "Vermont",
  [EUSState.VIRGIN_ISLANDS]: "Virgin Islands",
  [EUSState.VIRGINIA]: "Virginia",
  [EUSState.WASHINGTON]: "Washington",
  [EUSState.WEST_VIRGINIA]: "West Virginia",
  [EUSState.WISCONSIN]: "Wisconsin",
  [EUSState.WYOMING]: "Wyoming",
};
