import { Dictionary, EUSState } from "@neufund/shared";

import { TTranslatedString } from "../../types";

export const US_STATES: Dictionary<TTranslatedString, EUSState> = {
  [EUSState.ALABAMA]: "Alabama",
  [EUSState.ALASKA]: "Alaska",
  [EUSState.AMERICAN_SAMOA]: "American Samoa",
  [EUSState.ARIZONA]: "Arizona",
  [EUSState.ARKANSAS]: "Arkansas",
  [EUSState.CALIFORNIA]: "California",
  [EUSState.COLORADO]: "Colorado",
  [EUSState.CONNECTICUT]: "Connecticut",
  [EUSState.DELAWARE]: "Delaware",
  [EUSState.DISTRICT_OF_COLUMBIA]: "District Of Columbia",
  [EUSState.FEDERATED_STATES_OF_MICRONESIA]: "Federated States Of Micronesia",
  [EUSState.FLORIDA]: "Florida",
  [EUSState.GEORGIA]: "Georgia",
  [EUSState.GUAM]: "Guam",
  [EUSState.HAWAII]: "Hawaii",
  [EUSState.IDAHO]: "Idaho",
  [EUSState.ILLINOIS]: "Illinois",
  [EUSState.INDIANA]: "Indiana",
  [EUSState.IOWA]: "Iowa",
  [EUSState.KANSAS]: "Kansas",
  [EUSState.KENTUCKY]: "Kentucky",
  [EUSState.LOUISIANA]: "Louisiana",
  [EUSState.MAINE]: "Maine",
  [EUSState.MARSHALL_ISLANDS]: "Marshall Islands",
  [EUSState.MARYLAND]: "Maryland",
  [EUSState.MASSACHUSETTS]: "Massachusetts",
  [EUSState.MICHIGAN]: "Michigan",
  [EUSState.MINNESOTA]: "Minnesota",
  [EUSState.MISSISSIPPI]: "Mississippi",
  [EUSState.MISSOURI]: "Missouri",
  [EUSState.MONTANA]: "Montana",
  [EUSState.NEBRASKA]: "Nebraska",
  [EUSState.NEVADA]: "Nevada",
  [EUSState.NEW_HAMPSHIRE]: "New Hampshire",
  [EUSState.NEW_JERSEY]: "New Jersey",
  [EUSState.NEW_MEXICO]: "New Mexico",
  [EUSState.NEW_YORK]: "New York",
  [EUSState.NORTH_CAROLINA]: "North Carolina",
  [EUSState.NORTH_DAKOTA]: "North Dakota",
  [EUSState.NORTHERN_MARIANA_ISLANDS]: "Northern Mariana Islands",
  [EUSState.OHIO]: "Ohio",
  [EUSState.OKLAHOMA]: "Oklahoma",
  [EUSState.OREGON]: "Oregon",
  [EUSState.PALAU]: "Palau",
  [EUSState.PENNSYLVANIA]: "Pennsylvania",
  [EUSState.PUERTO_RICO]: "Puerto Rico",
  [EUSState.RHODE_ISLAND]: "Rhode Island",
  [EUSState.SOUTH_CAROLINA]: "South Carolina",
  [EUSState.SOUTH_DAKOTA]: "South Dakota",
  [EUSState.TENNESSEE]: "Tennessee",
  [EUSState.TEXAS]: "Texas",
  [EUSState.UTAH]: "Utah",
  [EUSState.VERMONT]: "Vermont",
  [EUSState.VIRGIN_ISLANDS]: "Virgin Islands",
  [EUSState.VIRGINIA]: "Virginia",
  [EUSState.WASHINGTON]: "Washington",
  [EUSState.WEST_VIRGINIA]: "West Virginia",
  [EUSState.WISCONSIN]: "Wisconsin",
  [EUSState.WYOMING]: "Wyoming",
};
