export const DEFAULT_DERIVATION_PATH_SUB_PREFIX_1 = "44'/60'/";
export const DEFAULT_DERIVATION_PATH_SUB_PREFIX_2 = "0'/0";
export const DEFAULT_DERIVATION_PATH_PREFIX =
  DEFAULT_DERIVATION_PATH_SUB_PREFIX_1 + DEFAULT_DERIVATION_PATH_SUB_PREFIX_2;
export const DEFAULT_LEDGER_ACCOUNTS_PER_PAGE = 10;
